# -*- coding: utf-8 -*-
"""cluster K-mean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11yUsQf_O7-O-yYsswQf6tlslU_MbfbTi
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

#Menyiapkan data dan memanggil dataset
dataset =pd.read_csv('UsiaDanPendapatanMember.csv')
dataset.keys()

dataku = pd.DataFrame(dataset)
dataku.head()

#konversi ke data Array
X = np.asarray(dataset)
print(X)

#Menampilkan data dalam bentuk scatter plot
plt.scatter(X[:,0], X[:,1], label='True position')
plt.xlabel("Umur")
plt.ylabel("Gaji")
plt.title("Grafik umur dan gaji Membersip")
plt.show()

#mengaktifkan  K-meas dengan jumlah  K=3
kmeans = KMeans(n_clusters=3)
kmeans.fit(X)

#Menampilkan nilai Centroid yang digenerate oleh algoritma
print(kmeans.cluster_centers_)

#Plot data Point
#Memvisualisasikan Hasil klasterisasi data membersip 
plt.scatter(X[:,0], X[:,1], c=kmeans.labels_, cmap='rainbow')
plt.xlabel("Umur")
plt.ylabel("Gaji")
plt.title("Grafik Hasil Kelasterisasi Data Umur dan Gaji membersip")
plt.show()

#plot data poin
#Memvisualisasikan hasil klasterisasi dengan centeroid dr masing2 klaster
plt.scatter(X[:,0], X[:,1], c=kmeans.labels_, cmap='rainbow')
plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], color='black' )
plt.xlabel("Umur")
plt.ylabel("Gaji")
plt.title("Grafik Hasil Kelasterisasi Data Umur dan Gaji membersip")
plt.show()